### ISSUE TITLE
[Request] implement get_mac_address_table method

### ISSUE THREAD

**Issue by lboue** [napalm-automation-community/napalm-dellos10#13]
Hello,

Could you please implement the _get_mac_address_table method_? It is a basic feature that [works on every supported driver](https://napalm.readthedocs.io/en/latest/support/index.html?highlight=mac%20address):
- EOS
- IOS
- IOSXR
- JUNOS
- NXOS
- NXOS_SSH

### NAPALM doc
Here is what you can get from the _[NAPALM docs:](https://napalm.readthedocs.io/en/latest/base.html?highlight=get_mac_address_table#napalm.base.base.NetworkDriver.get_mac_address_table)_ about the get_mac_address_table method.

Returns a lists of dictionaries. Each dictionary represents an entry in the MAC Address Table, having the following keys:

- mac (string)
- interface (string)
- vlan (int)
- active (boolean)
- static (boolean)
- moves (int)
- last_move (float)

### XML API test from CLI:

```
Switch# show mac address-table  | display-xml
<?xml version="1.0" encoding="UTF-8"?>
<rpc-reply>
  <bulk>
    <data>
      <fwd-table>
        <mac-addr>**:**:**:**:**:**</mac-addr>
        <vlan>vla**</vlan>
        <entry-type>dynamic</entry-type>
        <if-name>port-channel**</if-name>
      </fwd-table>
      <fwd-table>
        <mac-addr>**:**:**:**:**:**</mac-addr>
        <vlan>vla**</vlan>
        <entry-type>dynamic</entry-type>
        <if-name>port-channel**</if-name>
      </fwd-table>
      <fwd-table>
        <mac-addr>**:**:**:**:**:**</mac-addr>
        <vlan>vla**</vlan>
        <entry-type>dynamic</entry-type>
        <if-name>port-channel**</if-name>
      </fwd-table>
    <last-keys>
      <entry-type>static</entry-type>
      <mac-addr>**:**:**:**:fc:**</mac-addr>
      <vlan>vlan****</vlan>
    </last-keys>
  </bulk>
</rpc-reply>

```

Regards,
Ludovic

**Comment by skg-net** [comment]
https://github.com/napalm-automation-community/napalm-dellos10/pull/14
@lboue, please verify

**Comment by lboue** [comment]
Thanks, I will test 1.0.6 version ASAP.
