### ISSUE TITLE
Feature requet : get_interfaces / implement last_flapped 

### ISSUE THREAD

**Issue by lboue** [napalm-automation-community/napalm-dellos10#20]
Hello,

Could you implement last_flapped parameter in the get_interfaces method?
See
```
def get_interfaces(self):
        """Get interface details.
        last_flapped is not implemented
```

Regards,
Ludovic

**Comment by semaja2** [comment]
Whilst that comment is in the code, it appears to be implemented? Does it work as expected?

**Comment by javeedf** [comment]
yes already resolved
